language: python

python:
  - 3.6.4

services:
  - redis-server

addons:
  postgresql: "9.5"

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

before_script:
  - psql -c 'create database test_alloy;' -U postgres

script: make test
